config/routes.rb
Bookhub::Application.routes.draw do
  namespace :cms do

  end

  get "/home" , :controller=>"home",:action =>"home"
  get "/home/home"  =>redirect("/home"), :controller=>"home",:action =>"home"
  get "/bestresources",:controller=>"home",:action=>"bestresources"
  match "/jobprofile" ,:controller=>"home",:action=>"jobprofiles", :as => :jobprofile
  get "/jobnews",:controller=>"home",:action=>"jobnews"
  get"/download",:controller=>"home",:action=>"download"

  root :to =>'home#home'

  mount_browsercms
end

app/models/music.rb
class Music < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home

  end
  def jobnews

  end
  def contactus

  end
  def jobprofiles

  end
  def bestresources

  end
  def download

  end
 def sd

 end
 def ds
 end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_all_products.html.erb
<div id="products" class="content-section">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <h1 class="section-title">All Products</h1>
      </div> <!-- /.col-md-12 -->
    </div> <!-- /.row -->
    <div class="row">
      <div class="col-md-3 col-sm-6">
        <div class="product-item">
          <div class="item-thumb">
            <span class="note"><img src="assets/small_logo_1.png" alt=""></span>
            <div class="overlay">
              <div class="overlay-inner">
                <a href="#nogo" class="view-detail">Add to Cart</a>
              </div>
            </div> <!-- /.overlay -->
            <img src="assets/products/product1.jpg" alt="">
          </div> <!-- /.item-thumb -->
          <h3>Nunc Consectetur</h3>
          <span>Price: <em class="text-muted">$260.00</em> - <em class="price">$180.00</em></span>
        </div> <!-- /.product-item -->
      </div> <!-- /.col-md-3 -->
      <div class="col-md-3 col-sm-6">
        <div class="product-item">
          <div class="item-thumb">
            <span class="note"><img src="assets/small_logo_3.png" alt=""></span>
            <div class="overlay">
              <div class="overlay-inner">
                <a href="#nogo" class="view-detail">Add to Cart</a>
              </div>
            </div> <!-- /.overlay -->
            <img src="assets/products/product2.jpg" alt="">
          </div> <!-- /.item-thumb -->
          <h3>Donec Vitae Massa</h3>
          <span>Price: <em class="text-muted">$320.00</em> - <em class="price">$240.00</em></span>
        </div> <!-- /.product-item -->
      </div> <!-- /.col-md-3 -->
      <div class="col-md-3 col-sm-6">
        <div class="product-item">
          <div class="item-thumb">
            <span class="note"><img src="assets/small_logo_2.png" alt=""></span>
            <div class="overlay">
              <div class="overlay-inner">
                <a href="#nogo" class="view-detail">Add to Cart</a>
              </div>
            </div> <!-- /.overlay -->
            <img src="assets/products/product3.jpg" alt="">
          </div> <!-- /.item-thumb -->
          <h3>Fusce Dignissim Neque</h3>
          <span>Price: <em class="text-muted">$480.00</em> - <em class="price">$340.00</em></span>
        </div> <!-- /.product-item -->
      </div> <!-- /.col-md-3 -->
      <div class="col-md-3 col-sm-6">
        <div class="product-item">
          <div class="item-thumb">
            <span class="note"><img src="assets/small_logo_1.png" alt=""></span>
            <div class="overlay">
              <div class="overlay-inner">
                <a href="#nogo" class="view-detail">Add to Cart</a>
              </div>
            </div> <!-- /.overlay -->
            <img src="assets/products/product4.jpg" alt="">
          </div> <!-- /.item-thumb -->
          <h3>Mauris Adipiscing Enim</h3>
          <span>Price: <em class="text-muted">$260.00</em> - <em class="price">$140.00</em></span>
        </div> <!-- /.product-item -->
      </div> <!-- /.col-md-3 -->
      <div class="col-md-3 col-sm-6">
        <div class="product-item">
          <div class="item-thumb">
            <span class="note"><img src="assets/small_logo_3.png" alt=""></span>
            <div class="overlay">
              <div class="overlay-inner">
                <a href="#nogo" class="view-detail">Add to Cart</a>
              </div>
            </div> <!-- /.overlay -->
            <img src="assets/products/product5.jpg" alt="">
          </div> <!-- /.item-thumb -->
          <h3>Quisque Tincidunt</h3>
          <span>Price: <em class="text-muted">$350.00</em> - <em class="price">$220.00</em></span>
        </div> <!-- /.product-item -->
      </div> <!-- /.col-md-3 -->
      <div class="col-md-3 col-sm-6">
        <div class="product-item">
          <div class="item-thumb">
            <span class="note"><img src="assets/small_logo_1.png" alt=""></span>
            <div class="overlay">
              <div class="overlay-inner">
                <a href="#nogo" class="view-detail">Add to Cart</a>
              </div>
            </div> <!-- /.overlay -->
            <img src="assets/products/product6.jpg" alt="">
          </div> <!-- /.item-thumb -->
          <h3>Aliquam Malesuada</h3>
          <span>Price: <em class="text-muted">$470.00</em> - <em class="price">$330.00</em></span>
        </div> <!-- /.product-item -->
      </div> <!-- /.col-md-3 -->
      <div class="col-md-3 col-sm-6">
        <div class="product-item">
          <div class="item-thumb">
            <span class="note"><img src="assets/small_logo_2.png" alt=""></span>
            <div class="overlay">
              <div class="overlay-inner">
                <a href="#nogo" class="view-detail">Add to Cart</a>
              </div>
            </div> <!-- /.overlay -->
            <img src="assets/products/product7.jpg" alt="">
          </div> <!-- /.item-thumb -->
          <h3>Sed Eleifend Tortor</h3>
          <span>Price: <em class="text-muted">$620.00</em> - <em class="price">$460.00</em></span>
        </div> <!-- /.product-item -->
      </div> <!-- /.col-md-3 -->
      <div class="col-md-3 col-sm-6">
        <div class="product-item">
          <div class="item-thumb">
            <span class="note"><img src="assets/small_logo_3.png" alt=""></span>
            <div class="overlay">
              <div class="overlay-inner">
                <a href="#nogo" class="view-detail">Add to Cart</a>
              </div>
            </div> <!-- /.overlay -->
            <img src="assets/products/product8.jpg" alt="">
          </div> <!-- /.item-thumb -->
          <h3>Integer tincidunt</h3>
          <span>Price: <em class="text-muted">$840.00</em> - <em class="price">$720.00</em></span>
        </div> <!-- /.product-item -->
      </div> <!-- /.col-md-3 -->
    </div> <!-- /.row -->
  </div> <!-- /.container -->
</div> <!-- /#products -->

app/views/home/_contact_us.html.erb
<div id="contact" class="content-section">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <h1 class="section-title">Contact Us</h1>
      </div> <!-- /.col-md-12 -->
    </div> <!-- /.row -->
    <div class="row">
      <div class="col-md-offset-2 col-md-8 text-center bigger-text">
        <p>templatemo provides a lot of free website templates for everyone. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores, itaque vero facere laudantium voluptas temporibus mollitia nisi deleniti illo minima quisquam corporis possimus nesciunt.</p>
      </div>
      <div class="col-md-6 col-sm-6">
        <div id="map">
        </div>
      </div> <!-- /.col-md-6 -->
      <div class="col-md-6 col-sm-6">

        <div class="row contact-form">

          <fieldset class="col-md-6 col-sm-6">
            <input id="name" type="text" name="name" placeholder="Name">
          </fieldset>
          <fieldset class="col-md-6 col-sm-6">
            <input type="email" name="email" id="email" placeholder="Email">
          </fieldset>
          <fieldset class="col-md-12">
            <input type="text" name="subject" id="subject" placeholder="Subject">
          </fieldset>
          <fieldset class="col-md-12">
            <textarea name="comments" id="comments" placeholder="Message"></textarea>
          </fieldset>
          <fieldset class="col-md-12">
            <input type="submit" name="send" value="Send Message" id="submit" class="button">
          </fieldset>

        </div> <!-- /.contact-form -->

      </div> <!-- /.col-md-6 -->
    </div> <!-- /.row -->
  </div> <!-- /.container -->
</div> <!-- /#products -->

app/views/home/_footer.html.erb
<div class="site-footer">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-sm-6">
        <span>Copyright &copy; 2084 <a href="#">Company Name</a> - Designed by <a href="http://www.templatemo.com">templatemo</a></span>
      </div> <!-- /.col-md-6 -->
      <div class="col-md-6 col-sm-6">
        <ul class="social">
          <li><a href="#" class="fa fa-facebook"></a></li>
          <li><a href="#" class="fa fa-twitter"></a></li>
          <li><a href="#" class="fa fa-instagram"></a></li>
          <li><a href="#" class="fa fa-linkedin"></a></li>
          <li><a href="#" class="fa fa-rss"></a></li>
        </ul>
      </div> <!-- /.col-md-6 -->
    </div> <!-- /.row -->
  </div> <!-- /.container -->
</div> <!-- /.site-footer -->

app/views/home/_jobprofiles.html.erb
<div id="services" class="content-section">
  <div class="container">
    <div class="row">
      <div class="col-md-3 col-sm-6">
        <div class="service-item">
          <span class="service-icon first"></span>
          <h3>Easy Customization</h3>
          <p>Cras congue orci at diam condimentum, in dignissim tellus elementum. Praesent id mauris eu urna vehicula rutrum sed in elit. Sed sed urna porta, viverra lacus in.</p>
        </div> <!-- /.service-item -->
      </div> <!-- /.col-md-3 -->
      <div class="col-md-3 col-sm-6">
        <div class="service-item">
          <span class="service-icon second"></span>
          <h3>Web Design</h3>
          <p>Nulla in nunc elit. Etiam porttitor nibh et felis molestie fermentum. Ut quis diam porttitor, dictum dolor in, volutpat nulla. Phasellus egestas eu lacus eu pharetra.</p>
        </div> <!-- /.service-item -->
      </div> <!-- /.col-md-3 -->
      <div class="col-md-3 col-sm-6">
        <div class="service-item">
          <span class="service-icon third"></span>
          <h3>High Quality</h3>
          <p>Sprint is free responsive website template using HTML5 CSS3 and Bootstrap framework. Feel free to download, edit and use it for your websites.</p>
        </div> <!-- /.service-item -->
      </div> <!-- /.col-md-3 -->
      <div class="col-md-3 col-sm-6">
        <div class="service-item">
          <span class="service-icon fourth"></span>
          <h3>Professional Design</h3>
          <p>Morbi id nisi enim. Ut congue interdum pharetra facilisi. Aenean consectetur pellentesque mauris nec ornare. Nam tortor justo, rutrum ut condimentum.</p>
        </div> <!-- /.service-item -->
      </div> <!-- /.col-md-3 -->
    </div> <!-- /.row -->
  </div> <!-- /.container -->
</div> <!-- /#services -->

app/views/home/_new_products.html.erb
<div id="product-promotion" class="content-section">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <h1 class="section-title">New Products</h1>
      </div> <!-- /.col-md-12 -->
    </div> <!-- /.row -->
    <div class="row">
      <div class="col-md-2 col-sm-3">
        <div class="item-small">
          <img src="assets/promotion/promotion1.jpg" alt="Product 1">
          <h4>Nullam Non Ultrices Arcu</h4>
        </div> <!-- /.item-small -->
      </div> <!-- /.col-md-2 -->
      <div class="col-md-8 col-sm-6">
        <div class="item-large">
          <img src="assets/promotion/promotion2.jpg" alt="Product 2">
          <div class="item-large-content">
            <div class="item-header">
              <h2 class="pull-left">Fusce facilisis semper magna</h2>
                                <span class="pull-right">Rate: <i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i>
                                <i class="fa fa-star-half-o"></i></span>
              <div class="clearfix"></div>
            </div> <!-- /.item-header -->
            <p>Integer ac dui interdum, varius sem eu, vulputate ipsum. Donec fringilla, est ac hendrerit elementum, libero nulla sodales odio, a placerat urna lectus at sem. Vivamus vehicula accumsan orci a tempus. Vestibulum a augue iaculis, tincidunt lacus venenatis, aliquet ante. Sprint is <a href="#">free website template</a> that can be used for any purpose.<br><br>Aliquam iaculis lectus accumsan, egestas lorem ac, malesuada purus. Aenean in tincidunt libero. Etiam vitae dolor vel justo temllicitudin. Download free templates for your websites. Sed fermentum, neque in dignissim aliquam, quam ante pellentesque quam, posuere eros purus purus. Ut non est magna.</p>
          </div> <!-- /.item-large-content -->
        </div> <!-- /.item-large -->
      </div> <!-- /.col-md-8 -->
      <div class="col-md-2 col-sm-3">
        <div class="item-small">
          <img src="assets/promotion/promotion3.jpg" alt="Product 3">
          <h4>Morbi Sit Amt Lorem</h4>
        </div> <!-- /.item-small -->
      </div> <!-- /.col-md-2 -->
    </div> <!-- /.row -->
  </div> <!-- /.container -->
</div> <!-- /#product-promotion -->

app/views/home/_slider.html.erb
<div class="site-slider">
  <ul class="bxslider">
    <li>
      <img src="assets/slider/slide1.jpg" alt="slider image 1">
      <div class="container">
        <div class="row">
          <div class="col-md-12 text-right">
            <div class="slider-caption">
              <h2>Job Profiles</h2>
            </div>
          </div>
        </div>
      </div>
    </li>
    <li>
      <img src="assets/slider/slide2.jpg" alt="slider image 2">
      <div class="container caption-wrapper">
        <div class="slider-caption">
          <h2>Best Resources</h2>
        </div>
      </div>
    </li>
    <li>
      <img src="assets/slider/slide3.jpg" alt="slider image 3">
      <div class="container">
        <div class="row">
          <div class="col-md-12 text-right">
            <div class="slider-caption">
              <h2>Best Profiles</h2>
            </div>
          </div>
        </div>
      </div>
    </li>
    <li>
      <img src="assets/slider/slide4.jpg" alt="slider image 4">
      <div class="container">
        <div class="row">
          <div class="col-md-12 text-right">
            <div class="slider-caption">
              <h2></h2>
            </div>
          </div>
        </div>
      </div>
    </li>
    <li>
      <img src="assets/slider/slide5.jpg" alt="slider image 5">
      <div class="container">
        <div class="row">
          <div class="col-md-12 text-right">
            <div class="slider-caption">
              <h2>Download and use it for free</h2>
            </div>
          </div>
        </div>
      </div>
    </li>
  </ul> <!-- /.bxslider -->
  <div class="bx-thumbnail-wrapper">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div id="bx-pager">
            <a data-slide-index="0" href=""><img src="assets/slider/thumb1.jpg" alt="image 1" /></a>
            <a data-slide-index="1" href=""><img src="assets/slider/thumb2.jpg" alt="image 2" /></a>
            <a data-slide-index="2" href=""><img src="assets/slider/thumb3.jpg" alt="image 3" /></a>
            <a data-slide-index="3" href=""><img src="assets/slider/thumb4.jpg" alt="image 4" /></a>
            <a data-slide-index="4" href=""><img src="assets/slider/thumb5.jpg" alt="image 5" /></a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div> <!-- /.site-slider -->

app/views/home/bestresources.html.erb
<h1>Best Resources</h1>

app/views/home/download.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <title>Free BinaryNews Template For sNews</title>
  <meta http-equiv="content-type" content="text/html;charset=iso-8859-2" />
  <link rel="stylesheet" href="images/style.css" type="text/css" />
</head>
<body>
<div class="content">
  <div class="preheader">
    <div class="padding"> <a href="#">About</a>&nbsp; <a href="#">Contact</a> </div>
  </div>
  <div class="header">
    <div class="title">YOUR COMPANY NAME</div>
    <div class="slogan">Your Best Slogan Here</div>
  </div>
  <div id="nav">
    <ul>
      <li><a href="#">Home</a></li>
      <li><a href="#">Products</a></li>
      <li><a href="#">Archive</a></li>
      <li><a href="#">Affiliates</a></li>
      <li id="current"><a href="#">About</a></li>
      <li><a href="#">Contact</a></li>
    </ul>
  </div>
  <div class="main_content">
    <div class="sd_right">
      <div class="text_padding">
        <h2>BinaryNews</h2>
        sit amet consectetuer adipiscing elit. Donec libero. Suspendisse bibendum. Cras id urna. Morbi tincidunt, orci ac convallis aliquam, lectus turpis varius lorem, eu posuere nunc justo tempus leo. Donec mattis, purus nec placerat bibendum, dui pede condimentum odio. <br />
        <h2>Search</h2>
        <form method="post" action="#">
          <p>
            <input type="text" name="search" class="search" />
            <input type="submit" value="Go" class="submit" />
          </p>
        </form>
        <br />
        <h2>Last Articles</h2>
        <a href="#">Link to a article</a><br />
        <a href="#">Link to another article...</a><br />
        <br />
        <h2>Links</h2>
        <a href="#">www.solucija.com</a><br />
        <a href="#">ww.free-css-templates.com</a><br />
      </div>
    </div>
    <div class="sd_left">
      <div class="text_padding">
        <h2>About</h2>
        Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec libero. Suspendisse bibendum. Cras id urna. Morbi tincidunt, orci ac convallis aliquam, lectus turpis varius lorem, eu posuere nunc justo tempus leo. Donec mattis, purus nec placerat bibendum, dui pede condimentum odio, ac blandit ante orci ut diam. Cras fringilla magna. Phasellus suscipit, leo a pharetra condimentum, lorem tellus eleifend magna, eget fringilla velit magna id neque. Curabitur vel urna. In tristique orci porttitor ipsum. Aliquam ornare diam iaculis nibh. Proin luctus, velit pulvinar ullamcorper nonummy, mauris enim eleifend urna, congue egestas elit lectus eu est. Fusce et odio sit amet erat ullamcorper accumsan.Proin luctus, velit pulvinar ullamcorper nonummy, mauris enim eleifend urna, congue egestas elit lectus eu est. Fusce et odio sit amet erat ullamcorper accumsan.
        <p class="date"><img src="images/comment.gif" alt="" /> <a class="date" href="#">Comments(2)</a> <img src="images/timeicon.gif" alt="" /> 21.02.</p>
        <br />
        Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Morbi tincidunt, orci ac convallis aliquam, lectus turpis varius lorem, eu posuere nunc justo tempus leo. Donec mattis, purus nec placerat bibendum, dui pede condimentum odio, ac blandit ante orci ut diam. Cras fringilla magna. Phasellus suscipit, leo a pharetra condimentum, lorem tellus eleifend magna, eget fringilla velit magna id neque. Curabitur vel urna. In tristique orci porttitor ipsum. Aliquam ornare diam iaculis nibh. Proin luctus, velit pulvinar ullamcorper nonummy, mauris enim eleifend urna, congue egestas elit lectus eu est. Fusce et odio sit amet erat ullamcorper accumsan.Proin luctus, velit pulvinar ullamcorper nonummy, mauris enim eleifend urna, congue egestas elit lectus eu est. Fusce et odio sit amet erat ullamcorper accumsan.
        <p class="date"><img src="images/comment.gif" alt="" /> <a class="date" href="#">Comments(15)</a> <img src="images/timeicon.gif" alt="" /> 13.01.</p>
        <br />
      </div>
    </div>
    <div class="footer">
      <div class="padding"> Powered by <a href="http://snews.solucija.com" title="Single file CSS and XHTML valid CMS">sNews</a> | &copy; Copyright BinaryNews Template :: Design: <a href="http://www.free-css-templates.com/" title="Free CSS Templates">David Herreman</a> | <a href="rss/">RSS Feed</a> | <a href="http://jigsaw.w3.org/css-validator/check/referer">CSS</a> and <a href="http://validator.w3.org/check?uri=referer">XHTML</a> | <a href="#">Login</a> </div>
    </div>
  </div>
</div>
</body>
</html>

app/views/home/home.html.erb
<div id="front">
  <div class="site-header">

    <div class="container">
      <div class="row">
        <div class="col-md-4 col-sm-6 col-xs-6">
          <div id="templatemo_logo">
            <h1><a href="#" >BOOKHUB</a></h1>
          </div> <!-- /.logo -->
        </div> <!-- /.col-md-4 -->
        <div class="col-md-8 col-sm-6 col-xs-6">
          <a href="#" class="toggle-menu"><i class="fa fa-bars"></i></a>
          <div class="homenav" >
            <ul>
              <li><%= link_to 'HOME', home_home_path, :target => "_blank" %></li>
              <li><%= link_to 'Best Resources',home_bestresources_path%></li>
              <li><%= link_to 'Job Profiles', jobprofile_path, :target => "_blank" %></li>
              <li><%= link_to 'Job News', home_jobnews_path %> </li>
              <li><%= link_to 'Download', home_download_path %></li>
            </ul>
          </div> <!-- /.main-menu -->
        </div> <!-- /.col-md-8 -->
      </div> <!-- /.row -->
      <div class="row">
        <div class="col-md-12">
          <div class="responsive">
            <div class="main-menu">
              <ul>
                <li><a href="#jobprofiles">Home</a></li>
                <li><a href="#">Services</a></li>
                <li><a href="#products">Products</a></li>
                <li><a href="#contact">Contact</a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div> <!-- /.container -->
  </div> <!-- /.site-header -->
</div> <!-- /#front -->
<%= render :partial=>"home/slider" %>
<%= render :partial=>"home/jobprofiles"%>
<%= render :partial=>"home/new_products"%>
<%= render :partial=>"home/all_products"%>
<%= render :partial=>"home/contact_us"%>
<%= render :partial=>"home/footer"%>

app/views/home/jobnews.html.erb
<head>
  <title>APPPath</title>
</head>
<body>
    <p>
      <b>NAME:</b>
    </p>
    <p>
      <b>DESCRIPTION:</b>
    </p>
    <p>
      <b>PRICE:</b>
    </p>
    <p>
      <b>SELLER_ID:</b>
    </p>
    <p>
      <b>EMAIL:</b>
    </p>
    <p><b>IMG_URL:</b>
    </p>
</body>

app/views/home/jobprofiles.html.erb
<head>
  <style>
      .header{ height:280px;
          width:700px;
          margin:auto;
          text-align:center;
          border:2px solid transparent;
          background-color: #F5F5F5;
          border-radius:15px;
      }
      h1{
          color: #2e5b88;
      }
      #bar{ font-size:28px;
          height:50px;
          width: 320px;
          border:2px solid green;
          border-radius:15px;
      }
  </style>
</head>
<body>
<div class="header"><h1>Hundreds of Free <br>Manufacture Drug Coupons </h1>
  <div>
    <p>FOR PRESCRIPTION DRUGS AND NON-PRESCRIPTION DRUGS -<br> 100% FREE - ONLINE SINCE 2007 - NO ANNOYING SIGN- INS!</p>
    <input id="bar" type="text" placeholder="Search Drug Coupons"> <input type="submit" id="search-submit">
  </div>
</div>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MUSIC</title>      <%= stylesheet_link_tag "style.css" %>
  <%= stylesheet_link_tag    "application", :media => "all" %>

  <meta name="viewport" content="width=device-width">

  <link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet">

  <link rel="stylesheet" href="assets/bootstrap.min.css">
  <link rel="stylesheet" href="asstes/normalize.min.css">
  <link rel="stylesheet" href="assets/animate.css">
  <link rel="stylesheet" href="assets/font-awesome.min.css">
  <link rel="stylesheet" href="assets/templatemo_misc.css">
  <link rel="stylesheet" href="assets/templatemo_style.css">

  <script src="/assets/modernizr-2.6.2.min.js"></script>

  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<%= javascript_include_tag "application" %>

<script src="asstes/jquery-1.10.1.min.js"></script>
<script>window.jQuery || document.write('<script src="js/vendor/jquery-1.10.1.min.js"><\/script>')</script>
<script src="assets/jquery.easing-1.3.js"></script>
<script src="asstes/bootstrap.js"></script>
<script src="assets/plugins.js"></script>
<script src="assets/main.js"></script>
</body>
</html>

app/views/layouts/templates/default.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />

    <script src="/assets/modernizr-2.6.2.min.js"></script>
    <title><%= page_title %></title>
    <%= yield :html_head %>
  </head>
  <body style="margin: 0; padding: 0; text-align: center;">
    <%= cms_toolbar %>
    <div id="wrapper" style="width: 700px; margin: 0 auto; text-align: left; padding: 30px">
      Breadcrumbs: <%= render_breadcrumbs %>
      Main Menu: <%= render_menu %>
      <h1><%= page_title %></h1>
      <%= container :main %>

      <!-- templatemo 401 sprint -->
    </div>
  </body>
</html>